/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import Factory.*;
import static Test.TestCase7.masterLock;
import java.awt.Graphics2D;
import java.util.Vector;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

/**
 *
 * @author Shan_
 */
public class TestCase8 extends javax.swing.JFrame {

    /**
     * Draws a drone and laser on canvas. 
     * Once the add ball button is click it will draw a ball on the canvas.
     * Shows how they interact with each other.
     * When the toggle laser button is pressed the laser beam will be drawn on the canvas.
     * If the drone or ball hits the beam they are destroyed.
     * The drone and ball do not interact with the laser itself.
     * 
     */
    static Lock masterLock =  new ReentrantLock();
    Graphics2D graphics;
    Laser laser;
    Collider c;
    public TestCase8() {
        initComponents();
        graphics = (Graphics2D) canvas8.getGraphics();
        //Vector<BouncyBall> bbs = new Vector<BouncyBall>();
        
        Drone drone = new Drone(canvas8, 400,22,graphics,masterLock);
        Thread dThread = new Thread(drone);
        dThread.start();
        
        
        laser = new Laser(canvas8,graphics, masterLock);
        Thread lThread = new Thread(laser);
        lThread.start();
        
        c = new Collider(null,drone,null,null,laser,null, masterLock);
        Thread cThread = new Thread(c);
        cThread.start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas8 = new javax.swing.JPanel();
        laserButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        canvas8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout canvas8Layout = new javax.swing.GroupLayout(canvas8);
        canvas8.setLayout(canvas8Layout);
        canvas8Layout.setHorizontalGroup(
            canvas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        canvas8Layout.setVerticalGroup(
            canvas8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        laserButton.setBackground(new java.awt.Color(204, 255, 204));
        laserButton.setText("Toggle laser");
        laserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laserButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(204, 255, 204));
        addButton.setText("Add Ball");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(laserButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(canvas8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(laserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void laserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laserButtonActionPerformed
        // TODO add your handling code here:
        if(laser.getShoot()){
            laser.setShoot(false);
        }
        else{
            laser.setShoot(true);
        }
    }//GEN-LAST:event_laserButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        BouncyBall ball = new BouncyBall(300,22,50,50,canvas8,true,false,graphics,masterLock);
        Thread bThread = new Thread(ball);
        bThread.start();
        c.addBall(ball);
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestCase8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestCase8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestCase8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestCase8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestCase8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel canvas8;
    private javax.swing.JButton laserButton;
    // End of variables declaration//GEN-END:variables
}
